# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import enum
import typing
__all__ = [
    "Action",
    "CaptureChoice",
    "Card",
    "GameState",
    "IsmctsSettings",
    "LedgerEntry",
    "PimcSettings",
    "Player",
    "PublicObservation",
    "PublicView",
    "ResolvingSettings",
    "Solver",
]

@typing.final
class Action:
    r"""
    A player decision: play a hand card, resolve the drawn stock card, call
    Koi-Koi, or call Shōbu.
    """
    @property
    def kind(self) -> builtins.str:
        r"""
        "play_from_hand" | "resolve_stock" | "koi_koi" | "shobu".
        """
    @property
    def card(self) -> typing.Optional[Card]:
        r"""
        The played card for `play_from_hand`, else `None`.
        """
    @property
    def capture(self) -> typing.Optional[CaptureChoice]:
        r"""
        The capture choice for `play_from_hand`/`resolve_stock`, else `None`.
        """
    @property
    def action_key(self) -> builtins.int:
        r"""
        The canonical total-ordering key — stable across platforms and
        builds; sorts every evaluator/digest the same way.
        """
    @staticmethod
    def play_from_hand(card: Card, capture: CaptureChoice) -> Action:
        r"""
        Play `card` from the hand, taking `capture` on the field.
        """
    @staticmethod
    def resolve_stock(capture: CaptureChoice) -> Action:
        r"""
        Resolve the publicly drawn stock card against the field.
        """
    @staticmethod
    def koi_koi() -> Action:
        r"""
        Call Koi-Koi — continue the round for a bigger score.
        """
    @staticmethod
    def shobu() -> Action:
        r"""
        Call Shōbu — stop the round and bank the score.
        """
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: Action) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...

@typing.final
class CaptureChoice:
    r"""
    Which field cards a play or draw captures.
    """
    @property
    def kind(self) -> builtins.str:
        r"""
        "no_match" | "single" | "pair" | "triple".
        """
    @property
    def card(self) -> typing.Optional[Card]:
        r"""
        The chosen field card for `single`/`pair`, else `None`.
        """
    @staticmethod
    def no_match() -> CaptureChoice:
        r"""
        The card joins the field — no capture.
        """
    @staticmethod
    def single(card: Card) -> CaptureChoice:
        r"""
        Exactly one matching card on the field; capture it.
        """
    @staticmethod
    def pair(card: Card) -> CaptureChoice:
        r"""
        Two matching cards on the field; capture the chosen one.
        """
    @staticmethod
    def triple() -> CaptureChoice:
        r"""
        Three matching cards on the field; capture all of them.
        """
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: CaptureChoice) -> builtins.bool: ...

@typing.final
class Card:
    r"""
    One of the 48 Hanafuda cards, addressed by deck index `0..=47`
    (`month * 4 + index_in_month`).
    """
    @property
    def index(self) -> builtins.int:
        r"""
        The deck index `0..=47`.
        """
    @property
    def month(self) -> builtins.int:
        r"""
        The month index `0..=11` (January = 0).
        """
    @property
    def index_in_month(self) -> builtins.int:
        r"""
        The card's position inside its month `0..=3`.
        """
    def __new__(cls, index: builtins.int) -> Card:
        r"""
        Args:
        index (int): Deck index in `0..=47`.
        """
    def __repr__(self) -> builtins.str: ...
    def __eq__(self, other: Card) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...

@typing.final
class GameState:
    r"""
    A live Koi-Koi round state — the transition kernel's own object, so
    legality, phases, and scoring are exactly the bench's.
    """
    @property
    def redeals(self) -> builtins.int:
        r"""
        Redeals this state consumed — provenance for the deal stream.
        """
    @property
    def is_ended(self) -> builtins.bool:
        r"""
        `True` once the round has ended.
        """
    @property
    def phase(self) -> builtins.str:
        r"""
        "hand" | "stock" | "stop" | "ended".
        """
    @property
    def drawn(self) -> typing.Optional[Card]:
        r"""
        The publicly drawn card at a stock-resolution decision, else `None`.
        """
    @property
    def dealer(self) -> Player:
        r"""
        The dealer seat.
        """
    @property
    def active(self) -> Player:
        r"""
        The seat to move.
        """
    @property
    def turn(self) -> builtins.int:
        r"""
        Completed player-turns this round.
        """
    @property
    def round(self) -> builtins.int:
        r"""
        The match round index.
        """
    @property
    def score(self) -> tuple[builtins.int, builtins.int]:
        r"""
        The match score `(south, north)` — leg margin is `score[s] - score[n]`.
        """
    @property
    def field(self) -> builtins.list[Card]:
        r"""
        The field cards.
        """
    @property
    def stock_count(self) -> builtins.int:
        r"""
        Remaining stock size including any pinned drawn card.
        """
    @property
    def koi_koi_calls(self) -> tuple[builtins.int, builtins.int]:
        r"""
        Per-seat Koi-Koi call counts `(south, north)`.
        """
    @property
    def koi_koi_caller(self) -> typing.Optional[Player]:
        r"""
        The Koi-Koi caller seat, if any.
        """
    @property
    def last_yaku_score(self) -> tuple[builtins.int, builtins.int]:
        r"""
        Last recorded yaku score per seat `(south, north)`.
        """
    @staticmethod
    def deal(seed: builtins.int, ruleset: builtins.str = 'nintendo') -> GameState:
        r"""
        Deals a fresh round. Anomalies resolve like the referee's: instant
        wins settle immediately, voids redeal from the tagged stream.
        
        Args:
            seed (int): Deal seed.
            ruleset (str): "nintendo" (default) or "fuda_wiki".
        
        Returns:
            GameState: The dealt state.
        """
    def next_round(self, seed: builtins.int) -> GameState:
        r"""
        Deals the next round of the match, carrying dealer rotation and the
        match score forward. The current state must have ended.
        
        Args:
            seed (int): Deal seed for the next round's deck.
        """
    def legal_actions(self) -> builtins.list[Action]:
        r"""
        The kernel-legal actions for the seat to move.
        """
    def apply_action(self, action: Action) -> None:
        r"""
        Applies a legal action, mutating the state in place.
        
        Raises:
            ValueError: The kernel rejected the transition.
        """
    def hand(self, player: Player) -> builtins.list[Card]:
        r"""
        A seat's hand — full information; use `public_view` for the
        observer-relative snapshot a solver is allowed to see.
        """
    def leg_margin(self, player: Player) -> builtins.int:
        r"""
        The leg margin from `player`'s seat (`score[p] - score[opp]`).
        """
    def public_view(self, observer: Player) -> PublicView:
        r"""
        The observer-relative public snapshot of the current state.
        
        Args:
            observer (Player): The seat the snapshot is visible to.
        """

@typing.final
class IsmctsSettings:
    r"""
    ISMCTS settings — `solver.ismcts.*`.
    """
    @property
    def iterations(self) -> builtins.int:
        r"""
        Iterations per decision. Default: 10000.
        """
    @iterations.setter
    def iterations(self, value: builtins.int) -> None:
        r"""
        Iterations per decision. Default: 10000.
        """
    @property
    def score_norm(self) -> builtins.float:
        r"""
        Reward normalization bound. Default: 20.0.
        """
    @score_norm.setter
    def score_norm(self, value: builtins.float) -> None:
        r"""
        Reward normalization bound. Default: 20.0.
        """
    def __new__(cls) -> IsmctsSettings: ...

@typing.final
class LedgerEntry:
    r"""
    One recorded public action in a round's ledger.
    """
    @property
    def player(self) -> Player:
        r"""
        The acting seat.
        """
    @property
    def action(self) -> Action:
        r"""
        The action applied.
        """
    @property
    def drawn(self) -> typing.Optional[Card]:
        r"""
        The publicly drawn card a `resolve_stock` entry resolved — required
        on that kind, `None` on every other.
        """
    def __new__(cls, player: Player, action: Action, drawn: typing.Optional[Card] = None) -> LedgerEntry:
        r"""
        Args:
        player (Player): The acting seat.
        action (Action): The applied action.
        drawn (Card | None): The drawn card for `resolve_stock` entries.
        """

@typing.final
class PimcSettings:
    r"""
    PIMC settings — `solver.pimc.*`.
    """
    @property
    def max_simulations(self) -> builtins.int:
        r"""
        Determinizations sampled per decision. Default: 64.
        """
    @max_simulations.setter
    def max_simulations(self, value: builtins.int) -> None:
        r"""
        Determinizations sampled per decision. Default: 64.
        """
    @property
    def batch_size(self) -> builtins.int:
        r"""
        Rayon chunk size over the determinization list. Default: 32.
        """
    @batch_size.setter
    def batch_size(self, value: builtins.int) -> None:
        r"""
        Rayon chunk size over the determinization list. Default: 32.
        """
    @property
    def scoring_method(self) -> builtins.str:
        r"""
        "mean" or "win_rate". Default: "mean".
        """
    @scoring_method.setter
    def scoring_method(self, value: builtins.str) -> None:
        r"""
        "mean" or "win_rate". Default: "mean".
        """
    def __new__(cls) -> PimcSettings: ...

@typing.final
class PublicObservation:
    r"""
    The public observation a ledger-driven solver consumes: the deal-time
    view plus the ordered action ledger. Hidden cards never appear — the
    observation is exactly what the attested seat could see.
    """
    @property
    def entries(self) -> builtins.list[LedgerEntry]:
        r"""
        The ledger entries, in play order.
        """
    def __new__(cls, initial: PublicView) -> PublicObservation:
        r"""
        Args:
        initial (PublicView): The deal-time view for the observing seat —
            `state.public_view(seat)` immediately after the deal.
        """
    def push(self, entry: LedgerEntry) -> None:
        r"""
        Appends one applied action to the ledger.
        
        Args:
            entry (LedgerEntry): The recorded public action.
        """
    def __len__(self) -> builtins.int:
        r"""
        Number of recorded actions — `len(observation)`.
        """

@typing.final
class PublicView:
    r"""
    The observer-relative public snapshot — every public zone, no hidden
    cards. Obtained from `GameState.public_view(observer)`.
    """
    @property
    def observer(self) -> Player:
        r"""
        The seat this snapshot is visible to.
        """
    @property
    def dealer(self) -> Player:
        r"""
        The dealer seat.
        """
    @property
    def active(self) -> Player:
        r"""
        The seat to move.
        """
    @property
    def turn(self) -> builtins.int:
        r"""
        Completed player-turns this round.
        """
    @property
    def round(self) -> builtins.int:
        r"""
        The match round index.
        """
    @property
    def score(self) -> tuple[builtins.int, builtins.int]:
        r"""
        The match score `(south, north)`.
        """
    @property
    def phase(self) -> builtins.str:
        r"""
        "hand" | "stock" | "stop" | "ended".
        """
    @property
    def drawn(self) -> typing.Optional[Card]:
        r"""
        The publicly drawn card at a stock-resolution decision, else `None`.
        """
    @property
    def base_score(self) -> typing.Optional[builtins.int]:
        r"""
        The offered base score at a stop decision, else `None`.
        """
    @property
    def own_hand(self) -> builtins.list[Card]:
        r"""
        The observer's own hand.
        """
    @property
    def opponent_hand_count(self) -> builtins.int:
        r"""
        The opponent's hand size — a count, never the cards.
        """
    @property
    def field(self) -> builtins.list[Card]:
        r"""
        The field cards.
        """
    @property
    def captured(self) -> tuple[builtins.list[Card], builtins.list[Card]]:
        r"""
        The captured piles `(south, north)`.
        """
    @property
    def stock_count(self) -> builtins.int:
        r"""
        Stock size including any pinned drawn card.
        """
    @property
    def koi_koi_caller(self) -> typing.Optional[Player]:
        r"""
        The Koi-Koi caller seat, if any.
        """
    @property
    def koi_koi_calls(self) -> tuple[builtins.int, builtins.int]:
        r"""
        Per-seat Koi-Koi call counts `(south, north)`.
        """
    @property
    def last_yaku_score(self) -> tuple[builtins.int, builtins.int]:
        r"""
        Last recorded yaku score per seat `(south, north)`.
        """

@typing.final
class ResolvingSettings:
    r"""
    Resolving settings — `solver.resolving.*`.
    """
    @property
    def max_worlds(self) -> builtins.int:
        r"""
        Belief cap: opponent-hand worlds per resolve. Default: 12.
        """
    @max_worlds.setter
    def max_worlds(self, value: builtins.int) -> None:
        r"""
        Belief cap: opponent-hand worlds per resolve. Default: 12.
        """
    @property
    def max_nodes(self) -> builtins.int:
        r"""
        Compiled gadget-tree node budget. Default: 150000.
        """
    @max_nodes.setter
    def max_nodes(self, value: builtins.int) -> None:
        r"""
        Compiled gadget-tree node budget. Default: 150000.
        """
    @property
    def cfr_iterations(self) -> builtins.int:
        r"""
        CFR+ iterations over the gadget tree. Default: 60.
        """
    @cfr_iterations.setter
    def cfr_iterations(self, value: builtins.int) -> None:
        r"""
        CFR+ iterations over the gadget tree. Default: 60.
        """
    @property
    def max_decision_depth(self) -> builtins.int:
        r"""
        Decision-ply cap below each world root. Default: 3.
        """
    @max_decision_depth.setter
    def max_decision_depth(self, value: builtins.int) -> None:
        r"""
        Decision-ply cap below each world root. Default: 3.
        """
    @property
    def adaptive(self) -> builtins.bool:
        r"""
        Opponent-model reweight + archetype posterior. Default: True.
        """
    @adaptive.setter
    def adaptive(self, value: builtins.bool) -> None:
        r"""
        Opponent-model reweight + archetype posterior. Default: True.
        """
    @property
    def ox(self) -> builtins.bool:
        r"""
        OX exploitation arm — requires `adaptive`. Default: False.
        """
    @ox.setter
    def ox(self, value: builtins.bool) -> None:
        r"""
        OX exploitation arm — requires `adaptive`. Default: False.
        """
    @property
    def blueprint_artifact(self) -> typing.Optional[builtins.str]:
        r"""
        Blueprint artifact path for the certified gadget oracle; `None`
        selects the learned rollout oracle (empirical guard).
        """
    @blueprint_artifact.setter
    def blueprint_artifact(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Blueprint artifact path for the certified gadget oracle; `None`
        selects the learned rollout oracle (empirical guard).
        """
    @property
    def leaf_model(self) -> typing.Optional[builtins.str]:
        r"""
        Learned leaf evaluator for oracle leaves: `"builtin:handcrafted"`
        selects the deterministic fallback evaluator; any other value is an
        ONNX model path (requires a `leaf-ort` build). `None` prices leaves
        through the margin oracle.
        """
    @leaf_model.setter
    def leaf_model(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        Learned leaf evaluator for oracle leaves: `"builtin:handcrafted"`
        selects the deterministic fallback evaluator; any other value is an
        ONNX model path (requires a `leaf-ort` build). `None` prices leaves
        through the margin oracle.
        """
    def __new__(cls) -> ResolvingSettings: ...

@typing.final
class Solver:
    r"""
    The solver facade: configuration, build, and decision calls for every
    backend the engine ships.
    """
    @property
    def method(self) -> builtins.str:
        r"""
        The backend: "random", "heuristic", "ismcts", "pimc", "endgame",
        "resolving" (alias "resolving_adaptive"), "leaf_policy", or
        "archetype".
        """
    @method.setter
    def method(self, value: builtins.str) -> None:
        r"""
        The backend: "random", "heuristic", "ismcts", "pimc", "endgame",
        "resolving" (alias "resolving_adaptive"), "leaf_policy", or
        "archetype".
        """
    @property
    def archetype(self) -> typing.Optional[builtins.str]:
        r"""
        The scripted archetype name when `method == "archetype"`:
        "heuristic" | "materialist" | "yaku_chaser" | "banker" | "gambler" |
        "timid" | "random".
        """
    @archetype.setter
    def archetype(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        The scripted archetype name when `method == "archetype"`:
        "heuristic" | "materialist" | "yaku_chaser" | "banker" | "gambler" |
        "timid" | "random".
        """
    @property
    def ismcts(self) -> IsmctsSettings:
        r"""
        ISMCTS settings — `solver.ismcts.*`.
        """
    @property
    def pimc(self) -> PimcSettings:
        r"""
        PIMC settings — `solver.pimc.*`.
        """
    @property
    def resolving(self) -> ResolvingSettings:
        r"""
        Resolving settings — `solver.resolving.*`.
        """
    @property
    def leaf_model(self) -> typing.Optional[builtins.str]:
        r"""
        ONNX leaf-model path for `method == "leaf_policy"`; `None` selects
        the deterministic handcrafted evaluator.
        """
    @leaf_model.setter
    def leaf_model(self, value: typing.Optional[builtins.str]) -> None:
        r"""
        ONNX leaf-model path for `method == "leaf_policy"`; `None` selects
        the deterministic handcrafted evaluator.
        """
    @property
    def use_parallel(self) -> builtins.bool:
        r"""
        Root-parallel search where the backend supports it.
        """
    @use_parallel.setter
    def use_parallel(self, value: builtins.bool) -> None:
        r"""
        Root-parallel search where the backend supports it.
        """
    @property
    def log_level(self) -> builtins.str:
        r"""
        "error" | "warn" | "info" | "debug" | "trace".
        """
    @log_level.setter
    def log_level(self, value: builtins.str) -> None:
        r"""
        "error" | "warn" | "info" | "debug" | "trace".
        """
    @property
    def seed(self) -> builtins.int:
        r"""
        The master seed.
        """
    def __new__(cls, method: builtins.str, archetype: typing.Optional[builtins.str] = None, seed: typing.Optional[builtins.int] = None) -> Solver:
        r"""
        Creates a solver with default settings.
        
        Args:
            method (str): "random", "heuristic", "ismcts", "pimc", "endgame",
                "resolving" (alias "resolving_adaptive"), or "archetype".
            archetype (str | None): Required when `method == "archetype"`.
            seed (int | None): Master seed; a fresh one is drawn when omitted.
        """
    def build(self) -> None:
        r"""
        Builds the engine under the current settings.
        
        Returns:
            Solver: A built solver. Mutating settings afterwards requires
                another `build()` before deciding.
        """
    def find_best_action(self, state: GameState, observation: typing.Optional[PublicObservation] = None, solver_seed: typing.Optional[builtins.int] = None) -> typing.Optional[Action]:
        r"""
        Picks an action for the current state.
        
        Args:
            state (GameState): The decision state.
            observation (PublicObservation | None): The attested public
                observation — required by `resolving` (the ledger IS its
                input; omitting it fails rather than falling back), ignored
                by the other backends.
            solver_seed (int | None): Per-decision seed; defaults to the
                solver's master seed.
        
        Returns:
            Action | None: The chosen action; `None` on terminal states.
        """

@typing.final
class Player(enum.Enum):
    r"""
    The two seats. `South` is the conventional "observer" seat; `North` its
    opponent. Int comparisons work (`Player.South == 0`).
    """
    South = ...
    North = ...


__version__: builtins.str
